services:
  hex_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      platform: linux/arm64
    image: docker.mazi.lol/hex_backend:latest
    ports:
      - "8100:8000" # Map to a different host port (8100)

  hex_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platform: linux/arm64
    image: docker.mazi.lol/hex_frontend:latest
    ports:
      - "3100:3000" # Map to a different host port (3100)
