name: Build and Deploy Hex Fullstack App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.mazi.lol -u dockerPushUser --password-stdin

      - name: Build Hex Backend Image
        env:
          DOCKER_DEFAULT_PLATFORM: linux/arm64
        run: |
          docker compose -f docker-compose.yml build hex_backend

      - name: Push Hex Backend Image
        run: |
          docker push docker.mazi.lol/hex_backend:latest

      - name: Build Hex Frontend Image
        env:
          DOCKER_DEFAULT_PLATFORM: linux/arm64
        run: |
          docker compose -f docker-compose.yml build hex_frontend

      - name: Push Hex Frontend Image
        run: |
          docker push docker.mazi.lol/hex_frontend:latest

      - name: SSH into the server and run Ansible Playbook
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 49.12.98.103
          username: root
          key: ${{ secrets.ANSIBLE_SERVER_SSH_PRIVATE }}
          port: 22
          script: |
            ansible-playbook -i ~/ansible/hex_inventory.ini ~/ansible/hex_redeploy.yml
